apiVersion: v1
kind: Service
metadata:
  name: {{ template "nexus.fullname" . }}-service
spec:
  selector:
    app: {{ template "nexus.name" . }}
  ports:
    - name: application
      port: {{ .Values.nexus.nexusPort }}
  type: ClusterIP
